import Foundation
import MachOKit
import MachOBase

public protocol HeapMetadataHeaderProtocol: TypeMetadataLayoutPrefixProtocol, HeapMetadataHeaderPrefixProtocol, TypeMetadataHeaderBaseProtocol where Layout: HeapMetadataHeaderLayout {}
