import Foundation
import Testing
import MachOKit
import Semantic
@_spi(Support) @testable import SwiftPrinting
@_spi(Support) @testable import SwiftInterface
@testable import MachOTestingSupport
import MachOFixtureSupport

/// Coverage for the interface header block (evolution proposal 0008):
/// pure-value rendering (line composition, per-field omission, the
/// byte-stability contract of the absent date), the Mach-O fact factory,
/// and the `printRoot` wiring (leading header when configured, byte-stable
/// absence by default).
@Suite(.serialized)
final class InterfaceHeaderTests: MachOFileTests, @unchecked Sendable {
    override class var fileName: MachOFileName { .SymbolTestsCore }

    private func render(_ info: InterfaceHeaderInfo) -> SemanticString {
        renderComponents(InterfaceHeaderBlock(info))
    }

    @SemanticStringBuilder
    private func renderComponents(_ block: InterfaceHeaderBlock) -> SemanticString {
        block
    }

    // MARK: - Pure-value rendering

    @Test func fullInfoRendersEveryLine() {
        let info = InterfaceHeaderInfo(
            generatorName: "swift-section",
            generatorVersion: "1.2.3",
            imagePath: "/usr/lib/Example.dylib",
            uuid: UUID(uuidString: "269D2B6E-DB35-3B93-97E0-B1B71D0DB64E"),
            cpuDescription: "arm64e",
            fileTypeDescription: "dylib",
            generatedDate: nil,
            dispatchThunkCount: 42,
            includesUnrecoverableNotes: false
        )
        let rendered = render(info).string
        // Each line ends in a break, plus the trailing blank line that
        // separates the header from whatever follows.
        #expect(rendered == "// Generated by swift-section 1.2.3\n"
            + "// Image: /usr/lib/Example.dylib (arm64e, dylib)\n"
            + "// UUID: 269D2B6E-DB35-3B93-97E0-B1B71D0DB64E\n"
            + "// Library evolution: detected (42 dispatch thunks)\n"
            + "\n")
    }

    @Test func absentFieldsOmitTheirLines() {
        let info = InterfaceHeaderInfo(
            generatorName: "swift-section",
            generatorVersion: "1.2.3",
            includesUnrecoverableNotes: false
        )
        let rendered = render(info).string
        #expect(rendered == "// Generated by swift-section 1.2.3\n\n")
    }

    @Test func zeroThunkCountRendersNotDetected() {
        var info = InterfaceHeaderInfo(generatorName: "g", generatorVersion: "0", includesUnrecoverableNotes: false)
        info.dispatchThunkCount = 0
        #expect(render(info).string.contains("Library evolution: not detected (0 dispatch thunks)"))
    }

    @Test func unrecoverableNotesRenderTheDigest() {
        let info = InterfaceHeaderInfo(generatorName: "g", generatorVersion: "0", includesUnrecoverableNotes: true)
        let rendered = render(info).string
        #expect(rendered.contains("Not recoverable from the binary (omitted, not absent):"))
        #expect(rendered.contains("`T!` prints as `T?`"))
        #expect(rendered.contains("internal vs fileprivate"))
    }

    /// The byte-stability contract: no date field, no date line — the
    /// default everywhere (tests, snapshots, plain CLI runs).
    @Test func absentDateLeavesNoDateLine() {
        var info = InterfaceHeaderInfo(generatorName: "g", generatorVersion: "0", includesUnrecoverableNotes: false)
        #expect(!render(info).string.contains("Generated at"))
        info.generatedDate = Date(timeIntervalSince1970: 0)
        #expect(render(info).string.contains("Generated at: 1970-01-01T00:00:00Z"))
    }

    // MARK: - Mach-O fact factory

    @Test func factoryReadsMachOFacts() throws {
        let unsafeMachOFile = machOFile
        let info = InterfaceHeaderInfo(machO: unsafeMachOFile, generatorName: "swift-section", generatorVersion: "0.0.0")
        #expect(info.imagePath?.hasSuffix("SymbolTestsCore") == true)
        #expect(info.uuid != nil)
        #expect(info.cpuDescription == "arm64")
        #expect(info.fileTypeDescription == "dylib")
        // The fixture is a library-evolution Release build; its dispatch
        // thunks are what the `final` recovery (proposal 0006) rides on.
        #expect((info.dispatchThunkCount ?? 0) > 100)
    }

    // MARK: - printRoot wiring

    @Test func printRootLeadsWithHeaderWhenConfigured() async throws {
        let unsafeMachOFile = machOFile
        var configuration = SwiftInterfaceBuilderConfiguration(indexConfiguration: .init(showCImportedTypes: false))
        configuration.interfaceHeaderInfo = InterfaceHeaderInfo(
            machO: unsafeMachOFile,
            generatorName: "swift-section",
            generatorVersion: "0.0.0"
        )
        let builder = try SwiftInterfaceBuilder(configuration: configuration, eventHandlers: [], in: unsafeMachOFile)
        try await builder.prepare()
        let output = try await builder.printRoot().string
        #expect(output.hasPrefix("// Generated by swift-section 0.0.0\n"))
        #expect(output.contains("// Library evolution: detected ("))
    }

    @Test func defaultConfigurationEmitsNoHeader() async throws {
        let unsafeMachOFile = machOFile
        let builder = try SwiftInterfaceBuilder(configuration: .init(indexConfiguration: .init(showCImportedTypes: false)), eventHandlers: [], in: unsafeMachOFile)
        try await builder.prepare()
        let output = try await builder.printRoot().string
        #expect(output.hasPrefix("import "))
        #expect(!output.contains("// Generated by"))
    }
}
